language: python
python:
    - 2.7
    - 3.4
    - 3.5
install:
  - pip install tox
  - pip install -r requirements.txt -r test-requirements.txt
script:
  - tox
env:
  - TOXENV=pep8
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
